teslamotors/fleet-telemetry

.github/workflows/publish.yml

Add support for github tag generation.
Note that this step only runs on main branch and after build.yml github action is completed

feat(ci): Add CI for releasing git tags and publish to docker hub

---

.github/workflows/publish.yml

This PR moves the github tag publishing from PR merge to on demand

Publish git tag and docker images only when triggered manually

---

README.md

These badge links gives us realtime information of builds and even hyperlinks them to relevant sites

Use improved badges in README.md

---

cmd/main.go
config/config.go
config/config_initializer_test.go
config/config_test.go
config/test_configs_test.go
docker-compose.yml
server/monitoring/status_server.go
server/streaming/server.go
test/integration/config.json
test/integration/integration_test.go
test/integration/server_test.go

update unit and integration tests as well
https://github.com/teslamotors/fleet-telemetry/issues/17

Add status server on http port

---

Dockerfile
test/integration/Dockerfile
test/integration/pretest.sh

Revised the Dockerfiles to improve the use caching.
Dependencies are loaded prior to pulling in source code. I have also moved building the binary to the `test/integration/Dockerfile`. Then, the root `Dockerfile` can pull the binary from tagged image. This prevents needing to load dependencies twice.
`make integration` takes 2 minutes 15 seconds on every build.
`make integration` takes 58 seconds on all builds, unless there are changes to `go.mod` or `go.sum`.
That's some Plaid acceleration!
---
Side note: This makes use of BuildKit which replaces the legacy builder. It is the default builder in latest Docker version. This will still work for users not on latest Docker version as the environment variable `DOCKER_BUILDKIT` is set.
Closes #35

Revise Dockerfiles to use caching

---

docker-compose.yml

Fixes CVEs in Confluence Platform dependencies used in integration tests.
Security release notes from 2.2.1 -> 2.2.6
- [v2.2.2](https://support.confluent.io/hc/en-us/articles/9744629647764-Security-Release-Notes-for-CP-7-2-2)
- [v2.2.3](https://support.confluent.io/hc/en-us/articles/11720533378836-Security-Release-Notes-for-CP-7-2-3)
- [v2.2.4](https://support.confluent.io/hc/en-us/articles/13481185512980-Security-Release-Notes-for-CP-7-2-4)
- [v2.2.5](https://support.confluent.io/hc/en-us/articles/14631251578260-Security-Release-Notes-for-CP-7-2-5)
- [v2.2.6](https://support.confluent.io/hc/en-us/articles/17308847664148-Security-Release-Notes-for-CP-7-2-6)

upgrade confluence platform dependencies in integration tests

---

config/config_initializer_test.go
config/config_test.go
datastore/simple/logger_test.go
metrics/adapter/prometheus/prometheus_test.go
server/streaming/server_test.go
server/streaming/socket_test.go
telemetry/record_test.go
telemetry/serializer_test.go
test/integration/google_consumer_test.go
test/integration/integration_test.go
test/integration/server_test.go

* `Expect().To(Not(...))` -> `.NotTo(...)`
* `Expect().ToNot(...)` -> `.NotTo(...)`
* `Expect(err).To(BeNil())` -> `.NotTo(HaveOccurred())`
* `Expect(len(x)).To(Equal(0))` -> `Expect(x).To(BeEmpty())`
* `Expect(len(x)).To(Equal(y))` -> `Expect(x).To(HaveLen(y))`

Clean up test expectations a bit

---

telemetry/record.go
telemetry/record_test.go
test/integration/integration_test.go
test/integration/server_test.go

In preparation of vehicles sending their Location as a `protos.Location` value, the server can perform the string->Location transformation to ease the parsing burden on the `Payload` consumers.

Convert Location field to proper Location type

---

config/config_test.go
datastore/googlepubsub/publisher.go

When running on GCP with GKE, the preferred authentication is through [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity). 
GOOGLE_APPLICATION_CREDENTIALS env var is not required when using Workload Identity as the Google PubSub library automatically uses metadata server available on GCP.

Remove GOOGLE_APPLICATION_CREDENTIALS  or PUBSUB_EMULATOR_HOST check.

---

Makefile

The makefile is currently using docker compose v1 syntax. Switch it to v2.
`docker-compose` now becomes `docker compose`.
Learn more: https://docs.docker.com/compose/migrate/

use docker compose v2

---

datastore/simple/logger.go
telemetry/record.go
telemetry/record_test.go

In https://github.com/teslamotors/fleet-telemetry/pull/95, logger started printed records as protobuf bytes which is not that useful. This PR ensures that always json payload is logged, regardless of value of `transmit_decoded_records`

logger dispatcher logs payloads in json string

---

cmd/main.go
server/monitoring/metrics_server.go
server/monitoring/profile_server.go
server/streaming/server.go
server/streaming/server_test.go
test/integration/integration_test.go
test/integration/profiler_test.go
test/integration/server_test.go

Two endpoints should be on the profiler port rather than the main port: `gc_stats` and `live_profiler`. This is done by installing them on the default mux used by the profiler, rather than a custom mux passed on to the main server.
Once `live_profiler` is on the internal profiler port, we can remove the `127.0.0.1` remote-ip restriction to make it easier to use, given that the default base image is a no-login image.

Fix profiler port

---

README.md
tools/check_csr.sh

Adds a simple script to validate CSR submissions

Add check_csr.sh

---

README.md
tools/check_csr.sh
tools/check_server_cert.sh

Adds a script `tools/check_server_cert.sh` to validate client configs against telemetry servers.

Add check_server_cert.sh

---

README.md

Adding reference to fleet_telemetry_errors endpoint.
Also fixed broken link to fleet_telemetry_config create endpoint.

callout fleet_telemetry_errors endpoint in readme

---

README.md
cmd/main.go
config/config.go
config/config_test.go
docker-compose.yml

Earlier we had documentation which recommended to not set custom CA file. This PR enforces the restriction outside of integration tests

disallow setting custom CA outside integration tests

---

datastore/kafka/kafka.go

Logger object in kafka producer wasn't initialized

Fix empty logger error

---

server/streaming/socket.go

Check for rate limiter presence correctly
https://github.com/teslamotors/fleet-telemetry/issues/141

fix nil error when rate limiter is not defined

---

cmd/main.go
config/config.go
config/config_test.go
datastore/googlepubsub/publisher.go
datastore/kafka/kafka.go
datastore/kinesis/kinesis.go
datastore/simple/logger.go
datastore/zmq/zmq.go
server/airbrake/airbrake.go
telemetry/producer.go
telemetry/serializer_test.go

Report datastore errors to airbrake. Note that it will only dispatch errors to airbrake if its actually configured otherwise `func (a *AirbrakeHandler) ReportLogMessage` acts as a noop.

Integrate airbrake with datastore

---

README.md
cmd/main.go
config/config.go
config/config_test.go
config/test_configs_test.go

Allow setting `AIRBRAKE_API_KEY` environment variable so that key can be avoided being stored in plaintext. If the env variable is set, it will override whatever is stored in Airbrake.ProjectId field of config file.

Add airbrake project key environment variable

---

server/airbrake/airbrake.go
server/airbrake/airbrake_test.go

Errbit logs error like this
This format isn't useful. Making following changes
- `logType` is int. `logrus.AllLogType[logType]` will return value in string
- `err.Error()` extracts error message to be logged properly in airbrake

Fix airbrake notice message

---

datastore/kafka/kafka.go

Kafka allows you to send opaque entry which are used for post processing flows. we should only set that field if reliable ack workers are configured

Do not set opaque object if reliable ack workers are not set. This fixes a potential memory leak issue

---

telemetry/record.go

In datastore, we use [Length()](https://github.com/teslamotors/fleet-telemetry/blob/main/datastore/kafka/kafka.go#L91) to instrument payload size sent to them. However the value which was instrumented was the flatbuffer message. Fixing here to use the actual payload length

Fix metrics for dispatched record size

---

datastore/kafka/kafka.go

Currently we report on kafka metrics on .Produce(). However, there are scenarios that kafka delivery fails and we don't record those failures. Handling reporting of metrics based on producer events instead

Log and report kafka metrics after producing them

---

datastore/kafka/kafka.go

Adds a go routine which periodically tracks pending messages to be sent to the broker.

Add kafka metrics related to local queue size

---

README.md
config/config_initializer.go
docker-compose.yml
logger/logger.go
logger/logger_logrus_test.go
logger/no_op_logger.go

Please include a summary of the changes and the related issue.
Key changes:-
- Allow a way to suppress the logging messages related to tls handshake error logged [here](https://cs.opensource.google/go/go/+/master:src/net/http/server.go;l=1933?q=%22TLS%20handshake%20error%20from%20%22&ss=go%2Fgo).
- Remove unused anomaly logger method

Add support to suppress tls logging

---

config/config.go
config/config_initializer.go
config/config_initializer_test.go
config/test_configs_test.go
datastore/kafka/kafka.go
server/streaming/socket.go
test/integration/config.json

Confluent provides the channel interface to get delivery reports. We should use that to get kafka metrics

Use delivery channel to get kafka producer metrics

---

README.md
config/config.go
config/config_initializer.go
config/config_initializer_test.go
config/config_test.go
config/test_configs_test.go
datastore/googlepubsub/publisher.go
datastore/kafka/kafka.go
datastore/kinesis/kinesis.go
datastore/simple/logger.go
datastore/zmq/zmq.go
server/streaming/server.go
server/streaming/server_test.go
server/streaming/socket.go
server/streaming/socket_test.go
telemetry/producer.go
telemetry/record_test.go
telemetry/serializer.go
telemetry/serializer_test.go
test/integration/config.json
test/integration/integration_test.go

Implement reliable acks in fleet telemetry which will allow to signal back to the vehicle that the request was processed successfully

Add support for reliable acks based on configuration

---

.github/workflows/publish.yml

We already support publishing latest in vehicle-command https://github.com/teslamotors/vehicle-command/blob/main/.github/workflows/publish.yml#L49. Makes sense to support it here as well

Support docker publish with latest tag

---

README.md
config/config.go
config/config_initializer.go
config/config_initializer_test.go
datastore/simple/logger.go
datastore/simple/logger_test.go
datastore/simple/simple_suite_test.go
datastore/simple/transformers/payload.go
datastore/simple/transformers/payload_test.go
datastore/simple/transformers/transformers_suite_test.go
datastore/simple/transformers/utilities_test.go
datastore/simple/transformers/vehicle_alert.go
datastore/simple/transformers/vehicle_alert_test.go
datastore/simple/transformers/vehicle_error.go
datastore/simple/transformers/vehicle_error_test.go
telemetry/record.go
telemetry/record_test.go

When using the simple `logger` backend, logs are written to stdout. The `data` field is currently a string with the JSON representation of the received data. This converts the received data into proper types before logging, meaning the log line is all JSON.
Example log output before this change:
```json
{"data":"{\"data\":[{\"key\":\"Soc\", \"value\":{\"stringValue\":\"61.214\"}}], \"createdAt\":\"2024-08-25T00:54:18.761807867Z\", \"vin\":\"VIN\"}"}
```
And after:
```json
{"data":{"Soc":{"stringValue":"61.214"},"Vin":"VIN","CreatedAt":"2024-08-25T00:54:18.761807867Z"}}
```
---
A new option is introduced for `logger`:
`compact` allows for removing types from the output. Given the example above, the compact form is:
```json
{"data":{"Soc":"61.214","Vin":"VIN","CreatedAt":"2024-08-25T00:54:18 …
```

improve record log formatting

---

Dockerfile

Don't think we need root privileges to run fleet telemetry

use non root image for fleet telemetry

---

datastore/simple/logger.go
datastore/simple/logger_test.go
telemetry/record.go
telemetry/record_test.go

- It seems record logger is broken when `transmit_decoded_records` is set to true. 
- Most likely logger broke when when https://github.com/teslamotors/fleet-telemetry/pull/200 started using `GetProtoMessage` to get protobuf message for custom logging. The reason the current implementation is wrong is because `GetProtoMessage` operation wasn't idempotent. 
- This PR stores the proto message during record creation itself
- Added tests
Fixes  https://github.com/teslamotors/fleet-telemetry/issues/230

Handle logger when transmit_decoded_records is set to true

---

.github/workflows/build.yml
Dockerfile
go.mod
test/integration/Dockerfile

Bumping golang version to 1.23

bump golang version in code and ci pipeline

---

README.md

More friendly documentation & Added docs for vehicle connectivity

Added documentation for vehicle connectivity

---

README.md
cmd/main.go
config/config.go
config/config_test.go
datastore/googlepubsub/publisher.go

- to prevent hitting resource quota, create the google pubsub topic on startup and reuse it for future data transmissions
Fixes # (https://github.com/teslamotors/fleet-telemetry/issues/289)

create pubsub topic on startup if it doesn't exists

---

README.md
config/config.go

Improving documentation of transmit_decoded_records.
Fixes #256

document transmit_decoded_records configuration option

---

README.md
config/config.go
config/config_initializer.go
config/config_test.go
config/test_configs_test.go
server/streaming/socket.go
telemetry/record.go
test/integration/config.json

Adding metrics to track incoming signal usage

track signal usage for received messages

---

.github/workflows/publish.yml

https://github.com/teslamotors/fleet-telemetry/pull/345 didn't work. Bumping versions in github actions to see the release pipeline is fixed. I see some discussion in https://github.com/docker/buildx/issues/1986 and based on that, trying to see if bumping up versions fixes it

update build and push github action version

---

.github/workflows/publish.yml
Dockerfile
test/integration/Dockerfile

https://github.com/teslamotors/fleet-telemetry/pull/345 and https://github.com/teslamotors/fleet-telemetry/pull/346
didn't fix the issue. Upon investigating more. Looks like for some reason, latest image is having libsodium errors. Pinning release pipeline to old image and also reverting commits which didn't fix the issue

fix publishing of docker images

---

server/streaming/socket.go

Will be helpful to always have client id in debug logs

add sm.requestIdentity.DeviceID to debug log for reliable ack

---

config/config.go
config/config_test.go
config/test_configs_test.go

The logic for configuring reliable acks only enables acks for the last tx type processed.
If a configuration calls for Kafka reliable acks for both `errors` and `V`, only one of the tx types will have acks processed. This happens non-deterministically.
This PR handles reliable acks for multiple tx types properly.

fix reliable acks only processed for one tx type

---

Dockerfile

Stay on the go 1.23 series, but default to the latest released minor version. This way we're always pulling in the latest bug and security fixes. Already running this in our production setup without issues. Just looking to upstream it.

Always use latest go minor versions

---

test/integration/Dockerfile

I saw that PR being merged https://github.com/teslamotors/fleet-telemetry/pull/366
If we use `1.23` and not `1.23.0` we should also use the same version for test, in order to test and deploy at the same version.
But personally I do prefer fixed version to prevent any breaking build on a patch update.

test: update golang version

---

protos/vehicle_data.pb.go
protos/vehicle_data.proto

Add comment showing LifetimeEnergyUsedDrive is Semi-only

Add semi-truck only comment to LifetimeEnergyUsedDrive

---

README.md

Improve interval description.
- [X ] Documentation update
- [ X ] I have made corresponding updates to the documentation.

Improve interval description
