teslamotors/fleet-telemetry

- .github/workflows/publish.yml
Fixing dockerhub location for publishing
> Use correct dockerhub location

- .github/workflows/publish.yml
Allow publishing for multiple platform architectures
> Enable multi arch publishing

- README.md
Add chicklets for build and release states
> Add build and release status chicklets

- README.md
Docker tags are published here https://hub.docker.com/r/tesla/fleet-telemetry/tags
> add docker location and update sample deployment in readme

- server/streaming/socket.go
We've already done the "hard work" to parse out the client certificate into the socket manager request identity.  We simply forgot to clean up this old code that searched the context for the certificate.
> Remove unnecessary certificate from context lookup

- README.md
add helm chart installation section to README.md
> SNET-39960 add helm chart installation section to README.md

- README.md
- config/config.go
- config/config_test.go
- datastore/googlepubsub/publisher.go
- datastore/kafka/kafka.go
- datastore/kinesis/kinesis.go
- telemetry/producer.go
- telemetry/producer_test.go
- test/integration/config.json
- test/integration/integration_test.go
- test/integration/kinesis_consumer_test.go
This adds support for dynamic Kinesis stream configuration.  We will also support a more "run time" option with env variables.
> Support dynamic Kinesis stream names

- Dockerfile
- Dockerfile.integration
- docker-compose.yml
Reverted deployment dockerfile to what it was before #38.
> fix deployment pipeline

- Makefile
- README.md
Please include a summary of the changes and the related issue.
Missed the change in my previous PR https://github.com/teslamotors/fleet-telemetry/pull/79
> Add missing protobuf generator to makefile

- .github/workflows/build.yml
Fixed CI check for generated protos
> Fix ci check for generating protos

- Makefile
Cleanup old generated files before generating new files from protoc. This is so that we don't accidentally have stale files committed
> clean previously generated proto files before generating new ones

- README.md
Improve documentation of the tls config
- [ X ] Documentation update
- [ X ] I have made corresponding updates to the documentation.
> Add README.md tls ca_file note

- datastore/googlepubsub/publisher.go
Pubsub metrics were being produced incorrectly
> fix metrics publishing for pubsub

- config/config.go
- config/config_test.go
- docker-compose.yml
Instead of override CA file present in the server, this PR will accept incoming CA file and then append it inbuilt CA certs
> append custom ca if provided

- README.md
> improve documentation of setup steps

- README.md
Updated the README file so example openssl commands align on use of private key file name.
Fixes #134 
- [N/A] I have added/updated unit tests to cover my changes.
- [ N/A I have added/updated integration tests to cover my changes.
> Fix setup steps typo

- cmd/main.go
- config/config.go
- config/config_initializer.go
- config/config_test.go
- datastore/googlepubsub/publisher.go
- datastore/kafka/kafka.go
- datastore/kinesis/kinesis.go
- datastore/simple/logger.go
- datastore/zmq/zmq.go
- go.mod
- go.sum
- logger/logger.go
- logger/logger_logrus_test.go
- logger/logger_suite_test.go
- logger/no_op_logger.go
- metrics/adapter/statsd/statsd.go
- metrics/adapter/statsd/statsd_test.go
- metrics/metrics.go
- server/monitoring/metrics_server.go
- server/monitoring/profile_server.go
- server/monitoring/status_server.go
- server/streaming/helper_suite_test.go
- server/streaming/server.go
- server/streaming/server_test.go
- server/streaming/socket.go
- server/streaming/socket_test.go
- telemetry/record.go
- telemetry/record_test.go
- telemetry/serializer.go
- telemetry/serializer_test.go
Fleet telemetry has a config to set server logging in json mode [here](https://github.com/teslamotors/fleet-telemetry/blob/main/config/config.go#L78). However the logs aren't in json format. This PR formats all logs in json format if flag is set
before
```sh
time="2024-04-02T18:51:12Z" level=info msg=starting
time="2024-04-02T18:51:12Z" level=info msg=status_server_configured
time="2024-04-02T18:51:12Z" level=info msg=profiler_started
time="2024-04-02T18:51:12Z" level=info msg="registered kafka for namespace: tesla_telemetry"
time="2024-04-02T18:51:12Z" level=info msg="registered pubsub for project: test-project-id, namespace: tesla_telemetry"
time="2024-04-02T18:51:12Z" level=info msg="appending custom CA file :/etc/tesla/certs/server/vehicle_device.CA.cert"
```
now
```sh …
```
> Improve server logging in json format

- README.md
- cmd/main.go
- config/config.go
- docker-compose.yml
- go.mod
- go.sum
- server/airbrake/airbrake.go
- server/airbrake/airbrake_suite_test.go
- server/airbrake/airbrake_test.go
- server/middleware/wrapped_response_writer.go
- server/monitoring/status_server.go
- server/streaming/server.go
- server/streaming/server_test.go
- test/integration/config.json
- test/integration/errbit/apps.json
- test/integration/errbit/init_errbit.rake
- test/integration/errbit/site_configs.json
- test/integration/errbit/users.json
- test/integration/mongodb/mongo-init.js
Add support for [airbrake](https://www.airbrake.io/). In this branch, just adding airbrake to report on 5xx error codes. Also updated docker-compose to run [errbit](https://github.com/errbit/errbit) which is Airbrake compliant.
> Add airbrake integration

- cmd/main.go
Airbrake allows to send data when a panic is detected on server startup
> Configure airbrake to notify on panic

- README.md
Kafka documentation change based on support feedback.
> Add topics to kafka backends description

- datastore/simple/logger.go
- datastore/simple/logger_test.go
Now that we are no longer using json marshalling and unmarshalling, it makes sense to update logging names
> Update logging names

- server/monitoring/profile_server.go
> Remove unused param

- telemetry/record.go
- telemetry/record_test.go
Floating point values very close to zero are reported in scientific notation. Convert these into regular floating point notation.
> fix floats reported in scientific notation

- cmd/main.go
- config/config.go
- config/config_test.go
- datastore/googlepubsub/publisher.go
- datastore/kafka/kafka.go
- datastore/kinesis/kinesis.go
- datastore/simple/logger.go
- datastore/simple/logger_test.go
- telemetry/producer.go
- telemetry/serializer_test.go
Closes producers gracefully on shutdown if supported by the provider
> close producers on shutdown

- doc/all_licenses.txt
> update licenses file

- server/streaming/server.go
> fix typo in comment

- datastore/googlepubsub/publisher.go
- server/streaming/server.go
- Instead of masking error, this change will return the error message
- Adding missing labels in pubsub metrics
> return error if its present

- datastore/googlepubsub/publisher.go
Fixed logic partially in https://github.com/teslamotors/fleet-telemetry/commit/87dfaef8b35750968bee84605fce601b1cf19da9 but not completely
> Add label to not connected counter

- datastore/mqtt/mqtt.go
- datastore/mqtt/mqtt_payload.go
- datastore/mqtt/mqtt_test.go
- test/integration/mqtt_consumer_test.go
Looks like linting did not run on #220. Resolve the linting issues that occurred in post-merge build attempt.
cc @erwin314 
> fix mqtt linting errors

- config/config.go
- datastore/mqtt/mqtt.go
- docker-compose.yml
Perform health check on initialization of producer to verify MQTT server is reachable
> Perform health check of MQTT on startup

- README.md
A recent docs change moved virtual key instructions.
> update link to point to updated docs location

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/issue.md
Adding issue templates to vehicle-command repo, directing users to the new Fleet API Support page for all issues not directly related to this repo or project.
> Add issue templates to fleet-telemetry repo

- Dockerfile
- test/integration/Dockerfile
To handle failures like https://github.com/teslamotors/fleet-telemetry/actions/runs/13119594742
> install dependencies in image to get rid of build errors

- server/streaming/server.go
- telemetry/record.go
- telemetry/serializer.go
- test/integration/integration_test.go
- test/integration/server_test.go
In an upcoming firmware release, vehicles will begin including a `Version` header. This will indicate the capabilities of the vehicle in relation to fleet telemetry.
The aim of this is to abstract out the complicated branching structure when determining what fields/features a vehicle supports.
> add device client version

- protos/vehicle_data.proto
Update comments on vehicle_data proto to include 2024.45 minimum version.
> Update firmware version for 2024.44 fields to 2024.45

- docker-compose.yml
- test/integration/config.json
- test/integration/integration_test.go
Proposal: update kinesis docker image used in integration tests.
The current image [saidsef/aws-kinesis-local](https://github.com/saidsef/aws-kinesis-local) had only has 2 contributor and 21 stars, there is a risk it will go out of maintenance.
That's why I proposed to use localstack which has hundreads of contributors and over 50k stars, moreover this is under apache 2 license.
> tests(integration): update kinesis docker image

- docker-compose.yml
- test/integration/errbit/init_errbit.rake
- test/integration/errbit/init_errbit.sh
Latest errbit version has some issues in how we use it. Pinning it to an older version
> fix errbit startup

- protos/vehicle_data.pb.go
- protos/vehicle_data.proto
Adds minimum version comments for fields that require change-based streaming
> Add minimum version comments to change-based-only fields
